app/models/customer.rb, app/models/invoice.rb, app/models/invoice_item.rb, app/models/item.rb, app/models/merchant.rb, app/models/transaction.rb, db/migrate/20220104013105_create_customers.rb, db/migrate/20220104014422_create_invoices.rb, db/migrate/20220104020358_create_transactions.rb, db/migrate/20220104020606_create_merchant.rb, db/migrate/20220104020929_create_items.rb, db/migrate/20220104021309_create_invoice_items.rb, db/schema.rb, lib/tasks/csv_load.rake, spec/models/customer_spec.rb, spec/models/invoice_item_spec.rb, spec/models/invoice_spec.rb, spec/models/item_spec.rb, spec/models/merchant_spec.rb, spec/models/transaction_spec.rb
- Created all migrations
- Created rake tasks
- Created validations and relationships
- Created enums for Invoice and Invoice Items
=> Database setup

.gitignore, app/views/dashboard/index.html.erb, config/routes.rb, spec/features/merchants/dashboard_spec.rb
- Added 2 tests for second user story
- Added link views
- Added Gemfile.lock to gitignore
=> Add test and view for second user story

app/models/customer.rb, app/models/merchant.rb, app/views/dashboard/index.html.erb, spec/features/merchants/dashboard_spec.rb, spec/models/customer_spec.rb, spec/models/merchant_spec.rb
Features:
- Merchant dashboard displays top 5 customers based on number of transactions
- Merchant dashboard displays number of transactions with each customer next to name
Update:
- Validations for Merchant model to connect with customers
Tests:
- Add tests for model validations
- Add feature tests covering above criteria
=> User Story 3: Display top 5 customer names and transaction number

.gitignore, app/models/merchant.rb, app/views/dashboard/index.html.erb, spec/features/merchants/dashboard_spec.rb, spec/models/merchant_spec.rb
- Created test for items not shipped
- Added method for items not shipped
=> Dashboard 4

app/models/invoice_item.rb, app/models/merchant.rb, app/views/dashboard/index.html.erb, spec/features/merchants/dashboard_spec.rb, spec/models/invoice_item_spec.rb, spec/models/item_spec.rb, spec/models/merchant_spec.rb
Feature: 
- Merchant dashboard displays item invoices in order of oldest to newest 
- Displays invoice creation date
- Changed date format to display day of week, MM DD,YYYY
Updates:
- Updated logic in items not shipped method to order by invoice creation date 
- Updated view to use .invoice_id, not .id
Tests: 
- Wrote tests to cover invoice creation date display and formatting 
- Wrote tests to cover update in items not shipped
- Updated describe blocks in merchant model tests
=> User Story: Merchant Dashboard Invoices Sorted by Least Recent

app/controllers/invoices_controller.rb, app/models/invoice.rb, app/models/invoice_item.rb, app/views/invoices/index.html.erb, app/views/invoices/show.html.erb, app/views/items/show.html.erb, spec/features/merchants/invoices/index_spec.rb, spec/features/merchants/invoices/show_spec.rb, spec/features/merchants/items/show_spec.rb, spec/models/invoice_item_spec.rb, spec/models/invoice_spec.rb
Features:
- Merchant Invoices Index
- Merchant Invoices Show Page
- - Show page displays item information of all items for merchant looking at invoice
- - Show page displays invoice information
- - Show page displays total revenue earned from items for specific merchant
Add:
- #items_by_merchant to invoice.rb: passes merchant_id and returns all the items associated with that marchant for that invoice.
- #total_revenue_by_merchant to invoice.rb: passes merchant_id to items_by_merchant, then multiplies their unit_prices by their quantity and sums the resulting column.
Tests:
- Add model tests for invoice.rb
- Add feature tests for invoice_show and invoice_index
- Use let statements for test data creation
- Feature Tests and Model Tests are at 100% coverage by simple cov.
=> Invoices Index and Show Page

spec/features/merchants/items/index_spec.rb, spec/features/merchants/items/show_spec.rb
- Merged Enable/Disable and top item tests
- Changed the name for certain within blocks
=> Resolved merge errors

.gitignore, app/controllers/items_controller.rb, app/views/items/index.html.erb, app/views/items/new.html.erb, spec/features/merchants/items/index_spec.rb
- Create a form that creates a new item (added hidden field to have the status: enabled upon creation)
- Tests form
- Tests link
- Update and Create method
=> Merchant items create

app/controllers/admin/dashboard_controller.rb, app/controllers/dashboard_controller.rb, app/models/customer.rb, app/views/admin/dashboard/index.html.erb, app/views/dashboard/index.html.erb, app/views/layouts/partials/_top_customers.html.erb, config/routes.rb, spec/features/admin/dashboard/index_spec.rb, spec/features/merchants/dashboard_spec.rb, spec/models/customer_spec.rb
**Routes:**
-Added namespace admin route with merchant resource nested _(merge conflict expected)_
(admin_merchants_path goes to admin merchants index and admin_invoices_path goes to admin invoices index) _(merge conflict expected)_
CONTROLLERS:
Added an admin folder with a dashboard_controller inside (class Admin::DashboardController < ApplicationController)
VIEWS:
-New folders for admin/index
TEST:
Adds feature testing through admin/dashboard/index_spec.rb and 
Tests that merchants and invoices are links to their pages
FEATURES:
Admin sees links to invoices and merchants
**### UPDATE 1/9/22 -- Second merge is for the Admin Dashboard Top Customers
**Model:**
- Admin's top 5 class method created
**View**
Merchant Dashboard Index Page:
- Render partial top 5 merchant customers (we can use …
=> Admin dashboard

app/controllers/admin/merchants_controller.rb, app/models/merchant.rb, app/views/admin/merchants/edit.html.erb, app/views/admin/merchants/index.html.erb, app/views/admin/merchants/new.html.erb, app/views/admin/merchants/show.html.erb, config/routes.rb, db/migrate/20220108210016_add_status_to_merchants.rb, db/schema.rb, spec/features/admin/merchants/create_spec.rb, spec/features/admin/merchants/index_spec.rb, spec/features/admin/merchants/show_spec.rb, spec/features/admin/merchants/update_spec.rb, spec/models/merchant_spec.rb
BRANCH NOW INCLUDES ALL TESTS AND ASSOCIATED ELEMENTS FOR: 
1. Admin Merchants Update
2.  Admin Merchants Enable/Disable
3. Admin Merchants Grouped by status
4. Admin Merchants Create
5. Admin Merchants Top 5 Merchants
6. Admin Merchants top date for the top 5
ROUTES:
-Added namespace admin route with merchant resource nested 
(admin_merchants_path goes to admin merchants index and admin_merchant_path(merchant.id) goes to the show) 
CONTROLLERS: 
- Added an admin folder with a merchants_controller inside (class Admin::MerchantsController < ApplicationController)
VIEWS:
-New folders for admin/merchants, index and show files
TEST:
- Adds feature testing through admin/merchants/index_spec.rb and admin/merchants/show_spec.rb
- Tests that all merchants show on the index as links to their show …
=> User Stories Admin Merchants Index and Admin Merchants Show 

README.md
Worked on some updates to our README, including links to all of our githubs and linkedins, a description of the project, tools, and how to get it all set up, run the tests, deploy locally, and link to our heroku.
=> README: Draft

app/controllers/admin/invoices_controller.rb, app/views/admin/invoices/index.html.erb, spec/features/admin/invoices /index_spec.rb
-Added admin index test, view, and controller method.
=> Admin invoices

app/controllers/admin/invoices_controller.rb, app/controllers/items_controller.rb, app/views/admin/invoices/index.html.erb, app/views/items/edit.html.erb, app/views/items/show.html.erb, spec/features/admin/invoices /index_spec.rb, spec/features/merchants/items/show_spec.rb
-Add test for user story #33 
-Add form to edit.html.erb
-Add edit method to item controller & edit update method
- Add flash message to item show page
=> Merchant item update

app/controllers/admin/invoices_controller.rb, app/controllers/items_controller.rb, app/views/admin/invoices/index.html.erb, app/views/admin/invoices/show.html.erb, app/views/items/edit.html.erb, app/views/items/show.html.erb, spec/features/admin/invoices /index_spec.rb, spec/features/admin/invoices /show_spec.rb, spec/features/merchants/items/show_spec.rb
-Add test for admin Invoice show
-Add show page info for user stories #7 and #8 
-Add customer and Item access to show method in admin invoices controller
=> Admin invoice show

app/views/admin/merchants/index.html.erb, app/views/invoices/show.html.erb, app/views/items/index.html.erb, app/views/items/show.html.erb, spec/features/admin/merchants/index_spec.rb, spec/features/merchants/invoices/show_spec.rb, spec/features/merchants/items/index_spec.rb
Change from cents to dollars in views and tests
=> Currency fix

app/controllers/items_controller.rb, app/views/items/edit.html.erb, spec/features/merchants/invoices/update_spec.rb
Feature Update:
- Form pre-fills with existing item attribute information as per user-story (https://github.com/Sierra-T-9598/little-esty-shop/issues/33)
Test Update:
- Add merchant item update page spec file and tests covering page display and behavior
=> Fix: Merchant Item Update Page

app/controllers/invoices_controller.rb, app/controllers/items_controller.rb, app/views/admin/dashboard/index.html.erb, app/views/admin/invoices/index.html.erb, app/views/admin/invoices/show.html.erb, app/views/admin/merchants/edit.html.erb, app/views/admin/merchants/index.html.erb, app/views/admin/merchants/new.html.erb, app/views/admin/merchants/show.html.erb, app/views/dashboard/index.html.erb, app/views/invoices/index.html.erb, app/views/invoices/show.html.erb, app/views/items/edit.html.erb, app/views/items/index.html.erb, app/views/items/new.html.erb, app/views/items/show.html.erb, app/views/layouts/application.html.erb, app/views/layouts/partials/_admin_dashboard_links.html.erb, app/views/layouts/partials/_merchant_dashboard_links.html.erb
Added partials for admin dashboard links and merchant dashboard links so that any where you navigate, you will always have the option to return to one of these pages. 
Note- still no welcome page that allows us to start clicking links to navigate
=> Update: add partials for links at top of every page

app/models/customer.rb, app/models/invoice.rb, app/models/invoice_item.rb, app/models/item.rb, app/models/merchant.rb, app/models/transaction.rb, app/poros/commit.rb, app/views/layouts/application.html.erb, spec/features/admin/dashboard/index_spec.rb, spec/features/merchants/dashboard_spec.rb, spec/features/merchants/invoices/index_spec.rb, spec/features/merchants/items/show_spec.rb, spec/models/customer_spec.rb, spec/models/invoice_item_spec.rb, spec/models/invoice_spec.rb, spec/models/item_spec.rb, spec/models/merchant_spec.rb, spec/models/transaction_spec.rb
Update:
- all models now validate key information for their creation
Test:
- tests have been written to cover all validations
- test data has been re-written to include validated attributes
=> Update: Validations

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/poros/commit.rb, app/poros/github_search.rb, app/poros/pull_request.rb, app/poros/repo.rb, app/poros/user_info.rb, app/services/github_api.rb, app/services/github_service.rb, app/views/admin/invoices/show.html.erb, app/views/dashboard/index.html.erb, app/views/layouts/partials/_top_customers.html.erb, spec/features/admin/invoices/show_spec.rb
- Render invoice.status in Admin invoice show page after it has been updated
- Merge conflict expected
=> Refactor show

app/controllers/application_controller.rb, app/poros/commit.rb, app/poros/pull_request.rb, app/poros/repo.rb, app/services/github_api.rb, app/services/github_service.rb, app/views/layouts/application.html.erb
Features:
- Using GitHub API, our repository name displays in the footer of every page on our site.
- Using GitHub API, our team member names display in the footer of every page on our site.
- Using GitHub API, the number of commits each team member made are displayed next to each team member name in the footer of every page on our site. _This is limited to the last 100 commits by GitHub API._
- Using GitHub API, the total number of closed PRs is displayed in the footer of every page on our site. _This is limited to 100 pull requests by GitHub API._
Tests:
- Testing is not required for API consumption stories.
Update:
- Code to display API information and to run API actions in our controllers is currently commented out. This is to prevent running API requests for every test that navigates …
=> API User Stories

app/models/bulk_discount.rb, app/models/merchant.rb, db/migrate/20220114005458_create_bulk_discounts.rb, db/migrate/20220114005655_add_merchants_to_bulk_discounts.rb, db/schema.rb, spec/models/bulk_discount_spec.rb, spec/models/invoice_item_spec.rb, spec/models/merchant_spec.rb
One-to-many relationship between bulk discounts and merchants. 
Ran two migrations, one to create a discount table with columns of percentage discount and quantity threshold and one to add the foreign key of merchant_id to bulk discount table
=> Data: create bulk discounts table and relationship to merchants

app/controllers/merchants/bulk_discounts_controller.rb, app/views/merchants/bulk_discounts/index.html.erb, app/views/merchants/bulk_discounts/new.html.erb, spec/features/merchants/bulk_discounts/create_spec.rb, spec/features/merchants/bulk_discounts/index_spec.rb
Test: 
- Feature test in merchant bulk discounts index for new discount link 
- Feature test in for new form, through create_spec.rb
Views: 
- Link to new form on index view
-Added form_with model to a new bulk discount view
Controllers: 
- #new 
- #create
=> Merchant Bulk Discount Create

app/controllers/merchants/bulk_discounts_controller.rb, app/views/merchants/bulk_discounts/edit.html.erb, app/views/merchants/bulk_discounts/show.html.erb, spec/features/merchants/bulk_discounts/show_spec.rb, spec/features/merchants/bulk_discounts/update_spec.rb
Tests: 
- Feature test for link to edit form on the Merchant BD show page
- Feature test for form to edit the BD that prepopulates the fields and redirects back to show page with updated info 
Controllers: 
- edit action 
- update action 
Features: 
- Link to update on Merchant BD show page
- Page with a Form-with model to edit a bulk discount
=> Merchant Bulk Discount Edit

app/models/invoice.rb, app/models/invoice_item.rb, app/models/item.rb, app/models/merchant.rb, app/views/merchants/invoices/show.html.erb, spec/features/merchants/invoices/show_spec.rb, spec/models/invoice_spec.rb
Tests:
- Feature test for link to discount show page from merchant invoice show page
- Model test for #discount_items method on invoice to extract all items that qualified for a merchant discount
Updates: 
- added relationships to bulk discounts in item and invoice_item models. 
Features: 
- Link from invoice show page to discount show page 
- Method to collect all items that qualified for a discount, by the highest discount they qualified for
=> Merchants Invoice Show Page: Applied Discount Links

app/models/invoice.rb, app/views/admin/invoices/show.html.erb, spec/features/admin/invoices/show_spec.rb, spec/models/invoice_spec.rb
Tests: 
- Feature test for total discounted revenue on the admin/invoices/show page
- Model test for #total_discount on invoice
- Model test for #total_discounted_revenue on invoice (using invoice_item.revenue - total_discount)
Features: 
- Display total discounted revenue below total revenue on each admin/invoices/show page using #total_discounted_revenue
=> Admin Invoices Show Page: Total Discounted Revenue

spec/models/invoice_spec.rb
Made tests for examples 1-5 in project outline (invoice spec) to outline how and (how not) bulk discounts can apply.
=> Updates for testing

app/services/holiday_service.rb, app/views/layouts/application.html.erb, app/views/layouts/partials/_footer.html.erb, app/views/merchants/bulk_discounts/index.html.erb, spec/rails_helper.rb
Feature: Current view displays list of next 3 holidays on merchants bulk discount index page 
Test: in rails_helper, an rspec mock is used so that any instance of HolidayService leading to the API call, is mocked. 
Need updates: Install webmock gem to stub out any get requests for both APIs that little esty is consuming.
=> Nager.Date API

Gemfile, Gemfile.lock, spec/factories/bulk_discounts.rb, spec/factories/merchants.rb, spec/features/merchants/bulk_discounts/create_spec.rb, spec/rails_helper.rb
- This PR includes the addition of factory-bot and faker generated test data for the create_spec of bulk discounts. This was to get some familiarity with the tool, and will not be implemented across the app.
=> Update: implement factory-bot/faker gems in one spec to practice
